19) The SVD and the time taken to compute, as well as the reconstructed matrices to demonstrate correctness are all given below.

In [3]:
import numpy as np
import time

# Define the matrices
A1 = np.array([[2, 1],
               [1, 0]])

A2 = np.array([[2, 1],
               [1, 0],
               [0, 1]])

A3 = np.array([[2, 1],
               [-1, 1],
               [1, 1],
               [2, -1]])

A4 = np.array([[1, 1, 0],
               [-1, 0, 1],
               [0, 1, -1],
               [1, 1, -1]])


A5 = np.array([[0, 1, 1],
               [0, 1, 0],
               [1, 1, 0],
               [0, 1, 0],
               [1, 0, 1]])

In [5]:
# Compute the SVD for each matrix

start_time = time.time()
U, S, VT = np.linalg.svd(A1)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"SVD for Matrix A1:")
print("U:")
print(U)
print("Singular values:")
print(S)
print("VT:")
print(VT)
print(f"Time taken: {elapsed_time:.6f} seconds")
print()

SVD for Matrix A1:
U:
[[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]
Singular values:
[2.41421356 0.41421356]
VT:
[[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]
Time taken: 0.000000 seconds



In [6]:
# Compute the SVD for each matrix

start_time = time.time()
U, S, VT = np.linalg.svd(A2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"SVD for Matrix A2:")
print("U:")
print(U)
print("Singular values:")
print(S)
print("VT:")
print(VT)
print(f"Time taken: {elapsed_time:.6f} seconds")
print()

SVD for Matrix A2:
U:
[[-9.12870929e-01  5.55111512e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]
Singular values:
[2.44948974 1.        ]
VT:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
Time taken: 0.000000 seconds



In [7]:
start_time = time.time()
U, S, VT = np.linalg.svd(A3)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"SVD for Matrix A3:")
print("U:")
print(U)
print("Singular values:")
print(S)
print("VT:")
print(VT)
print(f"Time taken: {elapsed_time:.6f} seconds")
print()

SVD for Matrix A3:
U:
[[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]
Singular values:
[3.16227766 2.        ]
VT:
[[-1. -0.]
 [-0. -1.]]
Time taken: 0.000000 seconds



In [9]:
start_time = time.time()
U, S, VT = np.linalg.svd(A4)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"SVD for Matrix A4:")
print("U:")
print(U)
print("Singular values:")
print(S)
print("VT:")
print(VT)
print(f"Time taken: {elapsed_time:.6f} seconds")
print()

SVD for Matrix A4:
U:
[[-4.36435780e-01 -4.08248290e-01  7.07106781e-01 -3.77964473e-01]
 [ 4.36435780e-01  4.08248290e-01  7.07106781e-01  3.77964473e-01]
 [-4.36435780e-01  8.16496581e-01 -1.77001982e-16 -3.77964473e-01]
 [-6.54653671e-01 -7.49205180e-17 -1.19230075e-16  7.55928946e-01]]
Singular values:
[2.64575131 1.         1.        ]
VT:
[[-0.57735027 -0.57735027  0.57735027]
 [-0.81649658  0.40824829 -0.40824829]
 [ 0.          0.70710678  0.70710678]]
Time taken: 0.000000 seconds



In [11]:
start_time = time.time()
U, S, VT = np.linalg.svd(A5)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"SVD for Matrix A5:")
print("U:")
print(U)
print("Singular values:")
print(S)
print("VT:")
print(VT)
print(f"Time taken: {elapsed_time:.6f} seconds")
print()

SVD for Matrix A5:
U:
[[-5.47722558e-01 -5.49521713e-16 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01 -4.08248290e-01  5.43210215e-17 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01  4.24980527e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01 -4.08248290e-01  4.25921501e-17  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01  8.16496581e-01 -5.15968331e-16  1.32058463e-01
   4.27271064e-01]]
Singular values:
[2.23606798 1.41421356 1.        ]
VT:
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]
 [ 7.07106781e-01  3.86299829e-17 -7.07106781e-01]]
Time taken: 0.000000 seconds



In [19]:
matrices = [A1, A2, A3, A4, A5]

# Compute the SVD for each matrix and demonstrate correctness
for i, A in enumerate(matrices, start=1):
    U, S, VT = np.linalg.svd(A)

    # Reconstruct the original matrix
    A_reconstructed = np.dot(U[:, :len(S)], np.dot(np.diag(S), VT))

    print(f"Original Matrix A{i}:")
    print(A)
    print(f"Reconstructed Matrix A{i}:")
    print(A_reconstructed)
    print()


Original Matrix A1:
[[2 1]
 [1 0]
 [0 1]]
Reconstructed Matrix A1:
[[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00]
 [-1.66533454e-16  1.00000000e+00]]

Original Matrix A2:
[[ 2  1]
 [-1  1]
 [ 1  1]
 [ 2 -1]]
Reconstructed Matrix A2:
[[ 2.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 2. -1.]]

Original Matrix A3:
[[ 1  1  0]
 [-1  0  1]
 [ 0  1 -1]
 [ 1  1 -1]]
Reconstructed Matrix A3:
[[ 1.00000000e+00  1.00000000e+00  2.23711432e-17]
 [-1.00000000e+00 -3.10695764e-16  1.00000000e+00]
 [ 1.11022302e-16  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]]

Original Matrix A4:
[[ 1  1  0]
 [-1  0  1]
 [ 0  1 -1]
 [ 1  1 -1]
 [ 0  1  1]]
Reconstructed Matrix A4:
[[ 1.00000000e+00  1.00000000e+00  2.37095017e-16]
 [-1.00000000e+00 -5.29365856e-17  1.00000000e+00]
 [ 1.82215928e-16  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]
 [-3.39236419e-17  1.00000000e+00  1.00000000e+00]]

Original Matrix A5:
[[0 1 1]
 [0 1 