In [1]:
import numpy as np

# Define the coefficient matrices and the constant vectors for each system
A1 = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b1 = np.array([1, 0, 4])

A2 = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b2 = np.array([9, 7, 6])

A3 = np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8, -1], [0, 0, -1, 5]])
b3 = np.array([6, 25, -11, -11])

A4 = np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5, -1, -1], [-1, -1, -1, 4, 0], [0, 2, -1, 1, 4]])
b4 = np.array([6, 6, 6, 6, 6])

# Solve each system of equations
x1 = np.linalg.solve(A1, b1)
x2 = np.linalg.solve(A2, b2)
x3 = np.linalg.solve(A3, b3)
x4 = np.linalg.solve(A4, b4)

print("Solution to the first system:")
print(x1)
print("\nSolution to the second system:")
print(x2)
print("\nSolution to the third system:")
print(x3)
print("\nSolution to the fourth system:")
print(x4)


Solution to the first system:
[ 0.03508772 -0.23684211  0.65789474]

Solution to the second system:
[0.99578947 0.95789474 0.79157895]

Solution to the third system:
[-0.79764706  2.79529412 -0.25882353 -2.25176471]

Solution to the fourth system:
[ 0.78663239 -1.00257069  1.86632391  1.9125964   1.98971722]
